# Generated by Django 5.2.7 on 2025-10-24 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Author's first name", max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(help_text="Author's last name", max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('birth_date', models.DateField(blank=True, help_text="Author's date of birth", null=True)),
                ('nationality', models.CharField(blank=True, help_text="Author's nationality", max_length=100)),
                ('biography', models.TextField(blank=True, help_text='Brief biography of the author')),
                ('email', models.EmailField(blank=True, help_text="Author's contact email", max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='books_autho_last_na_7ca250_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('isbn', models.CharField(help_text='International Standard Book Number (ISBN)', max_length=13, unique=True)),
                ('publication_date', models.DateField(help_text='Date when the book was published')),
                ('publisher', models.CharField(blank=True, help_text='Publisher name', max_length=200)),
                ('pages', models.PositiveIntegerField(blank=True, help_text='Number of pages', null=True)),
                ('language', models.CharField(default='English', help_text='Language of the book', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description or synopsis of the book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(help_text='Authors who wrote this book', related_name='books', to='books.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-publication_date', 'title'],
                'indexes': [models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'), models.Index(fields=['publication_date'], name='books_book_publica_4f381a_idx')],
            },
        ),
    ]
